version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html/src
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  mysql:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  json-api:
    build:
      context: ./json-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./json-api:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: